export enum OrderStatus {
  PROCESSING = 'PROCESSING',
  WAIT_FOR_SHIPPING = 'WAIT_FOR_SHIPPING',
  PAYMENT_ERROR = 'PAYMENT_ERROR',
  REFUNDING = 'REFUNDING',
  REFUND_ERROR = 'REFUND_ERROR',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
  PAYING = 'PAYING',
  PAYMENT_ERROR = 'PAYMENT_ERROR',
  PAID = 'PAID',
  REFUNDING = 'REFUNDING',
  REFUND_ERROR = 'REFUND_ERROR',
  REFUNDED = 'REFUNDED',
}

export enum ShippingStatus {
  'WAIT_CONFIRM' = 'WAIT_CONFIRM',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',
}

export enum RentalStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  RETURNED = 'RETURNED',
  LATE = 'LATE',
  CANCELLED = 'CANCELLED',
}
